In [1]:
import theano

In [2]:
theano.__version__

'0.8.0'

# Baby Step

## Adding two vectors

In [3]:
import numpy
import theano.tensor as T
from theano import function
x = T.dscalar('x')
y = T.dscalar('y')
z = x + y
f = function([x, y], z)

In [4]:
f(2, 3)

array(5.0)

In [5]:
numpy.allclose(f(16.3, 12.1), 28.4)

True

In [9]:
from theano import pp
print(pp(z))

(x + y)


## Adding two matrices

In [10]:
x = T.dmatrix('x')
y = T.dmatrix('y')
z = x + y
f = function([x, y], z)

In [11]:
f([[1,2], [3,4]], [[10,20],[30,40]])

array([[ 11.,  22.],
       [ 33.,  44.]])

In [12]:
import numpy
f(numpy.array([[1,2], [3,4]]), numpy.array([[10,20],[30,40]]))

array([[ 11.,  22.],
       [ 33.,  44.]])

In [13]:
import theano
a = theano.tensor.vector()
out = a + a ** 10
f = theano.function([a], out)
print(f([0, 1, 2]))

[    0.     2.  1026.]


Solution to excerise

In [14]:
import theano
a = theano.tensor.vector()
b = theano.tensor.vector()
out = a**2 + b**2 + 2*a*b
f = theano.function([a, b], out)
print(f([0, 1, 2], [2,3,4]))

[  4.  16.  36.]
